/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually

    // tutorialSidebar: [
    //   'introduction',
    //   {
    //     type: 'category',
    //     label: 'Overview',
    //     items: [
    //       'guides/B&C',
    //       'guides/liquidity_protocol',
    //       'guides/stfil',
    //       'guides/borrowing',
    //       'guides/supplyEarning',
    //       'contract',
    //       'glossary',
    //     ],
    //   },
    //   {
    //     type: 'category',
    //     label: 'Guide',
    //     items: [
    //         'guide/emergency_model',
    //       'guide/debt',
    //     ],
    //   },
    //   {
    //     type: 'category',
    //     label: 'FDO',
    //     items: [
    //       {
    //         type: 'category',
    //         label: '治理',
    //         items: [
    //           'fdo/governance/info',
    //           'fdo/governance/fdo-structure',
    //           'fdo/governance/fdo-right',
    //           'fdo/governance/fdo-qualify',
    //           'fdo/governance/communication-channel',
    //           'fdo/governance/incentive'
    //         ]
    //       },
    //       {
    //         type: 'category',
    //         label: 'Proposal Intro',
    //         items: [
    //           'fdo/proposal/type',
    //           'fdo/proposal/template',
    //           'fdo/proposal/phase',
    //           'fdo/proposal/conflict_resolution',
    //           'fdo/proposal/other',
    //         ]
    //       },
    //       {
    //         type: 'category',
    //         label: 'Voting',
    //         items: [
    //           'fdo/vote/mechanism',
    //           'fdo/vote/process',
    //           'fdo/vote/entrust',
    //         ]
    //       },
    //       {
    //         type: 'link',
    //         label: 'Proposal',
    //         href: 'http://forum.stfil.io/',
    //       },
    //       {
    //         type: 'link',
    //         label: 'Discuss',
    //         href: 'http://forum.stfil.io/',
    //       }
    //     ],
    //   },
    //   {
    //     type: 'category',
    //     label: 'Developers',
    //     items: ['introduction'],
    //   },
    //   {
    //     type: 'category',
    //     label: 'milestones',
    //     items: [
    //       'milestones/Aquarius',
    //       'milestones/Bootes',
    //       'milestones/Capricorn',
    //       'milestones/Draco',
    //     ],
    //   },
    // ],
    //   myAutogeneratedSidebar: [
    //       {
    //           type: 'autogenerated',
    //           dirName: '.', // '.' 即当前的文档文件夹
    //       },
    //       {
    //           type: 'link',
    //           label: 'Proposal',
    //           href: 'http://forum.stfil.io/',
    //       },
    //       {
    //           type: 'link',
    //           label: 'Discuss',
    //           href: 'http://forum.stfil.io/',
    //       }
    //   ],
    // myAutogeneratedSidebar: [
    // {
    //     type: 'autogenerated',
    //     dirName: '.', // '.' 即当前的文档文件夹
    // },
    // {
    //     type: 'link',
    //     label: 'Proposal',
    //     href: 'https://forum.stfil.io/',
    // },
    // {
    //     type: 'link',
    //     label: 'Discuss',
    //     href: 'https://forum.stfil.io/',
    // }
    // ],
    overviewSidebar: [
        {
            type: 'autogenerated',
            dirName: 'overview', // '.' 即当前的文档文件夹
        }
    ],
    guidesSidebar: [
        {
            type: 'autogenerated',
            dirName: 'guides', // '.' 即当前的文档文件夹
        }
    ],
    fdoSidebar: [
        {
            type: 'autogenerated',
            dirName: 'fdo', // '.' 即当前的文档文件夹
        }
    ],
    devSidebar: [
        {
            type: 'autogenerated',
            dirName: 'development', // '.' 即当前的文档文件夹
        }
    ],
};

module.exports = sidebars;
